is_training: True
valid_move_reward: 5
check_reward: 10
win_lose_draw_reward:
  win: 1
  lose: -1
  draw: 0
turn_limit: 100
board_height: 400
board_width: 400
pawn_weight: 1
rook_weight: 1
knight_weight: 1
bishop_weight: 1
queen_weight: 1
level_update_frequency: 3.5e+4
wandb_run: False
stockfish_params:
  binary: "/usr/games/stockfish"
  wait_time: 100
  depth: 5
  engine_params:
    Debug Log File: ""
    Contempt: 0
    Min Split Depth: 0
    Threads: 1 # More threads will make the engine stronger, but should be kept at less than the number of logical processors on your computer.
    Ponder: "false"
    Hash: 16 # Default size is 16 MB. It's recommended that you increase this value, but keep it as some power of 2. E.g., if you're fine using 2 GB of RAM, set Hash to 2048 (11th power of 2).
    MultiPV: 1
    Skill Level: 0
    Move Overhead: 10
    Minimum Thinking Time: 20
    Slow Mover: 100
    UCI_Chess960: "false"
    UCI_LimitStrength: "false"
    UCI_Elo: 1350
